### ISSUE TITLE
Feature Request:  Highlight and/or Underline URL/URI text (and make clickable?)

### ISSUE THREAD

**Issue by jtbrown3** [jfcherng/Sublime-OpenUri#13]
Is it possible to have OpenUri highlight (and optionally underline) URL/URI text with either one of the color scheme colors or a user-specified color, and optionally make it clickable as well? 

Thanks for considering this! -JT

**Comment by jfcherng** [comment]
> Is it possible to have OpenUri highlight (and optionally underline) URL/URI text with either one of the color scheme colors or a user-specified color

Something like this, using the color of the `string` scope as the background color.
![image](https://user-images.githubusercontent.com/6594915/177714069-461f2c52-86f4-4903-9740-48c09fb92675.png)
```js
{
    // draw URI regions such as adding a underline?
    "draw_uri_regions": {
        // when to draw URI regions?
        // values can be
        //     - "always" (always draw)
        //     - "hover" (only when the URI is hovered)
        //     - "never" (never draw)
        "enabled": "always",
        // the scope used to highlight URI regions (you may customize it with your theme)
        "scope": "string",
        // icon in the gutter: "dot", "circle", "bookmark" or empty string for nothing
        "icon": "",
        // the draw flags used, see https://www.sublimetext.com/docs/api_reference.html
        "flags": [
            "HIDE_ON_MINIMAP",
            // "DRAW_SOLID_UNDERLINE",
            // "DRAW_NO_FILL",
            "DRAW_NO_OUTLINE",
        ],
    },
}
```


> optionally make it clickable as well?

If you don't like the default click-the-phantom way, you can default your own mouse binding.
https://github.com/jfcherng-sublime/ST-OpenUri#mouse-bindings
But the readme example is cheating that it actually calls ST's builtin functionality rathern than OpenUri's.

---

If you don't want ![image](https://user-images.githubusercontent.com/6594915/177714490-0994a096-4f98-401b-8ead-403b6afadcae.png), set `"show_open_button": "never",`.

**Comment by jtbrown3** [comment]
> > Is it possible to have OpenUri highlight (and optionally underline) URL/URI text with either one of the color scheme colors or a user-specified color
> 
> Something like this, using the color of the `string` scope as the background color. ![image](https://user-images.githubusercontent.com/6594915/177714069-461f2c52-86f4-4903-9740-48c09fb92675.png)
> 
> ```js
> {
>     // draw URI regions such as adding a underline?
>     "draw_uri_regions": {
>         // when to draw URI regions?
>         // values can be
>         //     - "always" (always draw)
>         //     - "hover" (only when the URI is hovered)
>         //     - "never" (never draw)
>         "enabled": "always",
>         // the scope used to highlight URI regions (you may customize it with your theme)
>         "scope": "string",
>         // icon in the gutter: "dot", "circle", "bookmark" or empty string for nothing
>         "icon": "",
>         // the draw flags used, see https://www.sublimetext.com/docs/api_reference.html
>         "flags": [
>             "HIDE_ON_MINIMAP",
>             // "DRAW_SOLID_UNDERLINE",
>             // "DRAW_NO_FILL",
>             "DRAW_NO_OUTLINE",
>         ],
>     },
> }
> ```
> 
> > optionally make it clickable as well?
> 
> If you don't like the default click-the-phantom way, you can default your own mouse binding. https://github.com/jfcherng-sublime/ST-OpenUri#mouse-bindings But the readme example is cheating that it actually calls ST's builtin functionality rathern than OpenUri's.
> 
> If you don't want ![image](https://user-images.githubusercontent.com/6594915/177714490-0994a096-4f98-401b-8ead-403b6afadcae.png), set `"show_open_button": "never",`.
_____________________________

Thanks again for your quick reply, Jack! 👍
So do I simply insert the above code into the "OpenUri.sublime-settings" file?
(edit:  I just confirmed the code IS in the settings file -  So I will test this tomorrow as it is 12:30am Pacific Time and I need some sleep)

Cheers, -JT 🔆

**Comment by jfcherng** [comment]
Close due to inactivity. If the issue persists, feel free t reopen.
